print output in ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,8 +28,9 @@ jobs:
 
       - name: Build
         run: |
-          output=$(godot --headless --export-release '${{ matrix.platform }}' 2>&1)
-          if echo "$output" | grep -q "SCRIPT ERROR"; then
-            echo "$output"
+          output=$(godot --headless --export-release '${{ matrix.platform }}' 2>&1) || exit_code=$?
+          echo "$output"
+
+          if [ "${exit_code:-0}" -ne 0 ] || echo "$output" | grep -q "SCRIPT ERROR"; then
             exit 1
           fi
